plugins/redmine_agile/config/routes.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :agile_queries, only: [:new, :create]
  resources :agile_charts_queries, only: [:new, :create]
  resources :agile_version_queries, only: [:new, :create, :edit, :update, :destroy]
  resources :agile_sprint_queries, only: [:new, :create, :edit, :update, :destroy]
  resources :agile_versions, only: [:index] do
    collection do
      get 'sprints'
      get 'load_more'
      get 'autocomplete'
    end
  end

  resources :agile_sprints
  get "get_story_points", :to => "agile_sprints#get_story_points"
end

resources :issues do
  get "done_ratio", :to => "agile_journal_details#done_ratio"
  get "status", :to => "agile_journal_details#status"
  get "assignee", :to => "agile_journal_details#assignee"
  member do
    get "agile_data", :to => "agile_boards#agile_data"
  end
end

resources :agile_queries
resources :agile_charts_queries, except: [:index, :show]
get '/agile_colors/:object_type', :to => "agile_colors#index", :as => "agile_colors"
put '/agile_colors/:object_type', :to => "agile_colors#update", :as => "update_agile_colors"

get '/projects/:project_id/agile/charts', :to => "agile_charts#show", :as => "project_agile_charts"
get '/agile/charts/', :to => "agile_charts#show", :as => "agile_charts"
get '/agile/charts/render_chart', :to => "agile_charts#render_chart"
get '/agile/charts/select_version_chart', :to => "agile_charts#select_version_chart"
get '/projects/:project_id/agile/board', :to => 'agile_boards#index'
get '/agile/board', :to => 'agile_boards#index'
put '/agile/board', :to => 'agile_boards#update', :as => 'update_agile_board'
get '/agile/board/backlog_load_more', :to => 'agile_boards#backlog_load_more', as: 'backlog_load_more_agile_boards'
get '/agile/board/backlog_autocomplete', :to => 'agile_boards#backlog_autocomplete', as: 'backlog_autocomplete_agile_boards'
get '/agile/issue_tooltip', :to => 'agile_boards#issue_tooltip', :as => 'issue_tooltip'
get '/agile/inline_comment', :to => 'agile_boards#inline_comment', :as => 'agile_inline_comment'
post 'projects/:project_id/agile/create_issue', :to => 'agile_boards#create_issue', :as => 'agile_create_issue'
get 'agile/issues/:id/edit', :to => 'agile_boards#edit_issue', :as => 'agile_edit_issue'
put 'agile/issues/:id/update', :to => 'agile_boards#update_issue', :as => 'agile_update_issue'

plugins/redmine_agile/app/models/agile_charts_query.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

class AgileChartsQuery < AgileQuery
  unloadable

  validate :validate_query_dates

  attr_writer :date_from, :date_to

  def initialize(attributes = nil, *args)
    super attributes
    self.filters.delete('status_id')
    self.filters['chart_period'] = { operator: 'm', values: [''] } unless has_filter?('chart_period')
  end

  self.operators_by_filter_type[:chart_period] = ['><', 'w', 'lw', 'l2w', 'm', 'lm', 'y']

  def initialize_available_filters
    super

    add_available_filter 'chart_period', type: :date_past, name: l(:label_date)
    add_available_filter 'sprint_id', type: :list, values: sprint_values, label: :label_agile_sprint
  end

  def sprint_values
    return [] unless project

    project.shared_agile_sprints.available.map { |s| [s.to_s, s.id.to_s] }
  end

  def default_columns_names
    @default_columns_names = [:id, :subject, :estimated_hours, :spent_hours, :done_ratio, :assigned_to]
  end

  def sql_for_chart_period_field(_field, _operator, _value)
    '1=1'
  end
  def sql_for_sprint_id_field(field, operator, value)
    if RUBY_VERSION < '2.4' && Redmine::VERSION.to_s < '3.3.0'
      value.map!(&:to_s)
    end

    sql_for_field(field, operator, value, AgileData.table_name, 'agile_sprint_id')
  end

  def chart
    @chart ||= RedmineAgile::Charts::Helper.valid_chart_name_by(options[:chart])
  end

  def chart=(arg)
    options[:chart] = arg
  end

  def date_from
    @date_from ||= chart_period[:from]
  end

  def date_to
    @date_to ||= chart_period[:to]
  end

  def interval_size
    if RedmineAgile::Charts::AgileChart::TIME_INTERVALS.include?(options[:interval_size])
      options[:interval_size]
    else
      RedmineAgile::Charts::AgileChart::DAY_INTERVAL
    end
  end

  def interval_size=(value)
    options[:interval_size] = value
  end

  def build_from_params(params)
    if params[:fields] || params[:f]
      self.filters = {}.merge(chart_period_filter(params))
      add_filters(params[:fields] || params[:f], params[:operators] || params[:op], params[:values] || params[:v])
    else
      available_filters.keys.each do |field|
        add_short_filter(field, params[field]) if params[field]
      end
    end
    self.group_by = params[:group_by] || (params[:query] && params[:query][:group_by])
    self.column_names = params[:c] || (params[:query] && params[:query][:column_names])
    self.date_from = params[:date_from] || (params[:query] && params[:query][:date_from])
    self.date_to = params[:date_to] || (params[:query] && params[:query][:date_to])
    self.sprint_id = params[:sprint_id] || (params[:query] && params[:query][:sprint_id])
    self.chart = params[:chart] || (params[:query] && params[:query][:chart]) || params[:default_chart] || RedmineAgile.default_chart
    self.interval_size = params[:interval_size] || (params[:query] && params[:query][:interval_size]) || RedmineAgile::Charts::AgileChart::DAY_INTERVAL
    self.chart_unit = params[:chart_unit] || (params[:query] && params[:query][:chart_unit]) || RedmineAgile::Charts::Helper::UNIT_ISSUES

    self
  end

  def condition_for_status
    '1=1'
  end

  private

  def chart_period_filter(params)
    return {} if (params[:fields] || params[:f]).include?('chart_period')
    sprint = project.shared_agile_sprints.where(id: params[:sprint_id]).first if project
    if sprint
      return { 'chart_period' => { operator: '><', values: [sprint.start_date.to_s, sprint.end_date.to_s] }, 'sprint_id' => { operator: '=', values: [sprint.id] } }
    end
    { 'chart_period' => { operator: 'm', values: [''] } }
  end

  def validate_query_dates
    if (self.date_from && self.date_to && self.date_from >= self.date_to)
      errors.add(:base, l(:label_agile_chart_dates) + ' ' + l(:invalid, scope: 'activerecord.errors.messages'))
    end
  end

  def db_timestamp_regex
    /(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(?:.\d*))/
  end

  def chart_period
    @chart_period ||= {
      from: chart_period_statement.match("chart_period > '#{db_timestamp_regex}") { |m| Time.zone.parse(m[1]) },
      to: chart_period_statement.match("chart_period <= '#{db_timestamp_regex}") { |m| Time.zone.parse(m[1]) }
    }
  end

  def chart_period_statement
    @chart_period_statement ||= build_chart_period_statement
  end

  def build_chart_period_statement
    field = 'chart_period'
    operator = filters[field][:operator]
    values = filters[field][:values]
    date = User.current.today

    case operator
    when 'w'
      first_day_of_week = (Setting.start_of_week || l(:general_first_day_of_week)).to_i
      day_of_week = date.cwday
      days_ago = (day_of_week >= first_day_of_week ? day_of_week - first_day_of_week : day_of_week + 7 - first_day_of_week)
      sql_for_field(field, '><t-', [days_ago], Issue.table_name, field)
    when 'm'
      date_to = RedmineAgile.chart_future_data? ? date.end_of_month.to_s : date.to_s
      sql_for_field(field, '><', [date.beginning_of_month.to_s, date_to], Issue.table_name, field)
    when 'y'
      days_ago = date - date.beginning_of_year
      sql_for_field(field, '><t-', [days_ago], Issue.table_name, field)
    when '><'
      sql_for_field(field, '><', adjusted_values(values), Issue.table_name, field)
    else
      sql_for_field(field, operator, values, Issue.table_name, field)
    end
  end

  def adjusted_values(values)
    return values unless values.is_a?(Array)

    from = values[0].present? ? Date.parse(values[0]) : Date.today
    to = values[1].present? ? Date.parse(values[1]) : Date.today
    [from.to_s, (to < from ? from : to).to_s]
  end
end

plugins/redmine_agile/app/controllers/agile_charts_queries_controller.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

class AgileChartsQueriesController < ApplicationController
  menu_item :agile

  before_action :find_query, except: [:index, :new, :create]
  before_action :find_optional_project, only: [:new, :create]

  helper :queries

  def new
    @query = AgileChartsQuery.new
    @query.user = User.current
    @query.project = @project
    @chart = params[:chart] || 'issues_burndown'
    unless User.current.allowed_to?(:manage_public_queries, @project) || User.current.admin?
      @query.visibility = AgileChartsQuery::VISIBILITY_PRIVATE
    end
    @query.build_from_params(params)
  end

  def create
    @query = AgileChartsQuery.new
    @query.user = User.current
    @query.project = params[:query_is_for_all] ? nil : @project
    @query.build_from_params(params)
    @query.name = params[:query] && params[:query][:name]
    if User.current.allowed_to?(:manage_public_queries, @project) || User.current.admin?
      @query.visibility = (params[:query] && params[:query][:visibility]) || AgileChartsQuery::VISIBILITY_PRIVATE
      @query.role_ids = params[:query] && params[:query][:role_ids] if Redmine::VERSION.to_s > '2.4'
    else
      @query.visibility = AgileChartsQuery::VISIBILITY_PRIVATE
    end

    if @query.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to_agile_chart(query_id: @query)
    else
      render action: 'new', layout: !request.xhr?
    end
  end

  def edit
  end

  def update
    @query.project = nil if params[:query_is_for_all]
    @query.build_from_params(params)
    @query.name = params[:query] && params[:query][:name]
    if User.current.allowed_to?(:manage_public_queries, @project) || User.current.admin?
      @query.visibility = (params[:query] && params[:query][:visibility]) || AgileChartsQuery::VISIBILITY_PRIVATE
      @query.role_ids = params[:query] && params[:query][:role_ids] if Redmine::VERSION.to_s > '2.4'
    else
      @query.visibility = AgileChartsQuery::VISIBILITY_PRIVATE
    end

    if @query.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to_agile_chart query_id: @query
    else
      render action: 'edit'
    end
  end

  def destroy
    @query.destroy
    redirect_to_agile_chart set_filter: 1
  end

private
  def find_query
    @query = AgileChartsQuery.find(params[:id])
    @project = @query.project
    render_403 unless @query.editable_by?(User.current)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_optional_project
    @project = Project.find(params[:project_id]) if params[:project_id]
    render_403 unless User.current.allowed_to?(:add_agile_queries, @project, global: true)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def redirect_to_agile_chart(options)
    options[:project_id] = @project if @project
    redirect_to agile_charts_path(options)
  end
end

plugins/redmine_agile/app/views/agile_charts_queries/_form.html.erb
<%= error_messages_for 'query' %>

<div class="box">
  <div class="tabular">
    <%= hidden_field_tag 'gantt', '1' if params[:gantt] %>

    <p>
      <label for="query_name"><%= l(:field_name) %></label>
      <%= text_field 'query', 'name', size: 80 %>
    </p>

    <% if User.current.admin? || User.current.allowed_to?(:manage_public_agile_queries, @project) %>
      <% if Redmine::VERSION.to_s < "2.4" %>
        <p><label for="query_is_public"><%= l(:field_is_public) %></label>
          <%= check_box 'query', 'is_public',
                        :onchange => (User.current.admin? ? nil : 'if (this.checked) {$("#query_is_for_all").removeAttr("checked"); $("#query_is_for_all").attr("disabled", true);} else {$("#query_is_for_all").removeAttr("disabled");}') %>
        </p>
      <% else %>
        <p><label><%= l(:field_visible) %></label>
          <label class="block"><%= radio_button 'query', 'visibility', Query::VISIBILITY_PRIVATE %> <%= l(:label_visibility_private) %></label>
          <label class="block"><%= radio_button 'query', 'visibility', Query::VISIBILITY_ROLES %> <%= l(:label_visibility_roles) %>
            :</label>
          <% Role.givable.sorted.each do |role| %>
            <label class="block role-visibility"><%= check_box_tag 'query[role_ids][]', role.id, @query.roles.include?(role), :id => nil %> <%= role.name %></label>
          <% end %>
          <label class="block"><%= radio_button 'query', 'visibility', Query::VISIBILITY_PUBLIC %> <%= l(:label_visibility_public) %></label>
          <%= hidden_field_tag 'query[role_ids][]', '' %>
        </p>
      <% end %>
    <% end %>

    <p><label for="query_is_for_all"><%= l(:field_is_for_all) %></label>
      <%= check_box_tag 'query_is_for_all', 1, @query.project.nil?,
                        :disabled => (!@query.new_record? && (@query.project.nil? || (@query.is_public? && !User.current.admin?))) %>
    </p>

    <fieldset>
      <legend><%= l(:label_options) %></legend>
      <p>
        <label for="chart"><%= l(:label_agile_chart) %></label>
        <%= select_tag 'chart', options_charts_for_select(query.chart), onchange: "toggleChartUnit($(this).val(), 'chart-unit-row');" %>
        <span id="chart-unit-row">
          <label for='chart_unit' style="margin-left: 0; float: none;"><%= l(:label_agile_chart_units) %></label>
          <%= select_tag 'chart_unit', options_chart_units_for_select(query.chart_unit) %>
        </span>
      </p>
      <p>
        <label for="interval_size"><%= l(:label_agile_interval_size) %></label>
        <%= select_tag 'interval_size', options_for_select(RedmineAgile::Charts::AgileChart::TIME_INTERVALS.map { |i| [l(:"label_agile_#{i}"), i] }, @query.interval_size) %>
      </p>
    </fieldset>
  </div>

  <fieldset id="filters">
    <legend><%= l(:label_filter_plural) %></legend>
    <%= render partial: 'queries/filters', locals: { query: query } %>
  </fieldset>
</div>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'redmine_agile', plugin: 'redmine_agile' %>
<% end %>

<%= javascript_tag do %>
  var chartsWithUnits = <%= raw RedmineAgile::Charts::Helper::CHARTS_WITH_UNITS.to_json %>
  $(document).ready(function() {
    $("input[name='query[visibility]']").change(function() {
    var checked = $('#query_visibility_1').is(':checked');
    $("input[name='query[role_ids][]'][type=checkbox]").attr('disabled', !checked);
    }).trigger('change');

    toggleChartUnit($('#chart').val(), 'chart-unit-row');
    hideChartPeriodCheckbox();
  });
<% end %>

plugins/redmine_agile/app/views/agile_charts_queries/edit.html.erb
<h2><%= l(:label_agile_chart_edit) %></h2>

<%= form_tag(agile_charts_query_path(@query), method: :put) do %>
  <%= render partial: 'form', locals: { query: @query } %>
  <%= submit_tag l(:button_save) %>
<% end %>

plugins/redmine_agile/app/views/agile_charts_queries/new.html.erb
<h2><%= l(:label_agile_chart_new) %></h2>

<%= form_tag(@project ? project_agile_charts_queries_path(@project) : agile_charts_queries_path) do %>
  <%= render partial: 'form', locals: { query: @query } %>
  <%= submit_tag l(:button_create) %>
<% end %>