plugins/redmine_agile/config/routes.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :agile_queries, only: [:new, :create]
  resources :agile_charts_queries, only: [:new, :create]
  resources :agile_version_queries, only: [:new, :create, :edit, :update, :destroy]
  resources :agile_sprint_queries, only: [:new, :create, :edit, :update, :destroy]
  resources :agile_versions, only: [:index] do
    collection do
      get 'sprints'
      get 'load_more'
      get 'autocomplete'
    end
  end

  resources :agile_sprints
  get "get_story_points", :to => "agile_sprints#get_story_points"
end

resources :issues do
  get "done_ratio", :to => "agile_journal_details#done_ratio"
  get "status", :to => "agile_journal_details#status"
  get "assignee", :to => "agile_journal_details#assignee"
  member do
    get "agile_data", :to => "agile_boards#agile_data"
  end
end

resources :agile_queries
resources :agile_charts_queries, except: [:index, :show]
get '/agile_colors/:object_type', :to => "agile_colors#index", :as => "agile_colors"
put '/agile_colors/:object_type', :to => "agile_colors#update", :as => "update_agile_colors"

get '/projects/:project_id/agile/charts', :to => "agile_charts#show", :as => "project_agile_charts"
get '/agile/charts/', :to => "agile_charts#show", :as => "agile_charts"
get '/agile/charts/render_chart', :to => "agile_charts#render_chart"
get '/agile/charts/select_version_chart', :to => "agile_charts#select_version_chart"
get '/projects/:project_id/agile/board', :to => 'agile_boards#index'
get '/agile/board', :to => 'agile_boards#index'
put '/agile/board', :to => 'agile_boards#update', :as => 'update_agile_board'
get '/agile/board/backlog_load_more', :to => 'agile_boards#backlog_load_more', as: 'backlog_load_more_agile_boards'
get '/agile/board/backlog_autocomplete', :to => 'agile_boards#backlog_autocomplete', as: 'backlog_autocomplete_agile_boards'
get '/agile/issue_tooltip', :to => 'agile_boards#issue_tooltip', :as => 'issue_tooltip'
get '/agile/inline_comment', :to => 'agile_boards#inline_comment', :as => 'agile_inline_comment'
post 'projects/:project_id/agile/create_issue', :to => 'agile_boards#create_issue', :as => 'agile_create_issue'
get 'agile/issues/:id/edit', :to => 'agile_boards#edit_issue', :as => 'agile_edit_issue'
put 'agile/issues/:id/update', :to => 'agile_boards#update_issue', :as => 'agile_update_issue'

plugins/redmine_agile/app/controllers/agile_versions_controller.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

class AgileVersionsController < ApplicationController
  unloadable

  menu_item :agile_backlog

  before_action :find_project_by_project_id
  before_action :authorize, except: [:autocomplete, :load_more]
  before_action :find_version, only: [:load_more]
  before_action :find_sprint, only: [:load_more]
  before_action :retrieve_query
  before_action :retrieve_data

  helper :queries
  include QueriesHelper
  helper :sort
  include SortHelper
  helper :issues
  include IssuesHelper
  helper :agile_boards
  include AgileBoardsHelper
  include RedmineAgile::Helpers::AgileHelper
  helper :agile_sprints
  include AgileSprintsHelper

  def index
    respond_to do |format|
      format.html
      format.js
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def sprints
    respond_to do |format|
      format.html
      format.js
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def autocomplete
    @more_url = load_more_project_agile_versions_path(@project, { q: params[:q], page: @paginator.try(:next_page) }.merge(@object_params))
    render layout: false
  end

  def load_more
    @more_url = load_more_project_agile_versions_path(@project, { q: params[:q], page: @paginator.try(:next_page) }.merge(@object_params))
    render layout: false
  end

  private

  def sprint_request?
    params[:sprints] || action_name == 'sprints'
  end

  def retrieve_query
    if sprint_request?
      retrieve_versions_query(AgileSprintsQuery, :sprints_query)
    else
      retrieve_versions_query(AgileVersionsQuery, :versions_query)
    end
  end

  def retrieve_data
    if sprint_request?
      @tab_sprints = true
      @issues = @sprint ? find_sprint_issues : find_no_sprint_issues
      @object_params = { sprint_id: @sprint.try(:id), sprints: 1 }
    else
      @tab_versions = true
      @issues = @version ? find_version_issues : find_no_version_issues
      @object_params = { version_id: @version.try(:id) }
    end
  end

  def find_version
    return unless params[:version_id]
    @version = Version.visible.where(id: params[:version_id]).first
    return render_404 unless @version
  end

  def find_version_issues
    scope = @query.version_issues(@version)
    @paginator = @query.version_paginator(@version, params)
    @version_issues = scope.offset(@paginator.offset).limit(@paginator.per_page).all
  end

  def find_no_version_issues
    scope = @query.no_version_issues(params)
    @paginator = @query.version_paginator(nil, params)
    @no_version_issues = scope.offset(@paginator.offset).limit(@paginator.per_page).all
  end

  def find_sprint
    return unless params[:sprint_id]
    @sprint = @project.shared_agile_sprints.where(id: params[:sprint_id]).first
    return render_404 unless @sprint
  end

  def find_sprint_issues
    scope = @query.sprint_issues(@sprint)
    @paginator = @query.sprint_paginator(@sprint, params)
    @sprint_issues = scope.offset(@paginator.offset).limit(@paginator.per_page).all
  end

  def find_no_sprint_issues
    scope = @query.no_sprint_issues(params)
    @paginator = @query.sprint_paginator(nil, params)
    @no_sprint_issues = scope.offset(@paginator.offset).limit(@paginator.per_page).all
  end
end

plugins/redmine_agile/app/helpers/agile_versions_helper.rb
# encoding: utf-8
#
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

module AgileVersionsHelper
  def version_select_tag(version, option = {})
    return '' if version.blank?
    version_id = version.is_a?(Version) && version.id || version
    other_version_id = option[:other_version].is_a?(Version) && option[:other_version].id || option[:other_version]
    select_tag('version_id', options_for_select(versions_collection_for_select, selected: version_id, disabled: other_version_id),
                             data: { remote: true,
                                     method: 'get',
                                     url: load_agile_versions_path(version_type: option[:version_type],
                                                                   other_version_id: other_version_id,
                                                                   project_id: @project) }) +
    content_tag(:span, '', :class => "hours header-hours #{option[:version_type]}-hours")
  end

  def versions_collection_for_select
    @project.shared_versions.open.map { |version| [format_version_name(version), version.id.to_s] }
  end

  def estimated_hours(issue)
    "%.2fh" % issue.estimated_hours.to_f
  end

  def estimated_value(issue)
    return (issue.story_points || 0) if RedmineAgile.use_story_points?
    issue.estimated_hours.to_f || 0
  end

  def estimated_unit
    RedmineAgile.use_story_points? ? 'sp' : 'h'
  end

  def column_version_class(tab_version, object)
    if tab_version
      object ? ".version-#{object.id}-issues" : '.no-version-issues'
    else
      object ? ".sprint-#{object.id}-issues" : '.no-sprint-issues'
    end
  end

  def agile_version_query_links(title, queries, sprints = false)
    return '' if queries.empty?
    # links to #index on issues/show
    url_params = { controller: 'agile_versions', action: sprints ? 'sprints' : 'index', project_id: @project}

    content_tag('h3', title) + "\n" +
      content_tag('ul',
        queries.collect { |query|
            css = 'query'
            css << ' selected' if query == @query
            content_tag('li', link_to(query.name, url_params.merge(query_id: query), class: css))
          }.join("\n").html_safe,
        class: 'queries'
      ) + "\n"
  end

  def sidebar_agile_version_queries
    unless @sidebar_agile_version_queries
      @sidebar_agile_version_queries = AgileVersionsQuery.visible.
                                       order("#{Query.table_name}.name ASC").
                                       where('project_id IS NULL OR project_id = ?', @project.id).
                                       all
    end
    @sidebar_agile_version_queries
  end

  def sidebar_agile_sprint_queries
    unless @sidebar_agile_sprint_queries
      @sidebar_agile_sprint_queries = AgileSprintsQuery.order("#{Query.table_name}.name ASC").
                                       where('project_id IS NULL OR project_id = ?', @project.id).
                                       all
    end
    @sidebar_agile_sprint_queries
  end

  def render_sidebar_agile_version_queries
    out = ''.html_safe
    out << agile_version_query_links(l(:label_agile_version_my_boards), sidebar_agile_version_queries.reject(&:is_public?))
    out << agile_version_query_links(l(:label_agile_version_board_plural), sidebar_agile_version_queries.select(&:is_public?))
    out
  end

  def render_sidebar_agile_sprint_queries
    out = ''.html_safe
    out << agile_version_query_links(l(:label_agile_sprint_my_boards), sidebar_agile_sprint_queries.reject(&:is_public?), true)
    out << agile_version_query_links(l(:label_agile_sprint_board_plural), sidebar_agile_sprint_queries.select(&:is_public?), true)
    out
  end
end

plugins/redmine_agile/app/views/agile_versions/_filters_form.html.erb
<%= form_tag(form_url, method: :get, id: 'query_form') do %>
  <div id="query_form_with_buttons" class="hide-when-print">
    <%= hidden_field_tag 'set_filter', '1' %>
    <div id="query_form_content">
      <fieldset id="filters" class="collapsible <%= query.new_record? ? "" : "collapsed" %>">
        <legend onclick="toggleFieldset(this);" class="icon icon-<%= @query.new_record? ? "expanded" : "collapsed" %>"><%= l(:label_filter_plural) %></legend>
        <div style="<%= query.new_record? ? "" : "display: none;" %>">
          <%= render partial: 'queries/filters', locals: {query: query} %>
        </div>
      </fieldset>
      <fieldset id="options" class="collapsible collapsed">
        <legend onclick="toggleFieldset(this);" class="icon icon-collapsed"><%= l(:label_options) %></legend>
        <div style="display: none;">
          <table class="options">
            <tr>
              <td><%= l(:label_agile_fields) %></td>
              <td class="card-fields">
                <%= render_board_fields_selection(query) %>
              </td>
            </tr>
          </table>
        </div>
      </fieldset>
    </div>
    <p class="buttons">
      <%= link_to_function l(:button_apply), '$("#query_form").submit()', class: 'icon icon-checked' %>
      <%= link_to l(:button_clear), { set_filter: 1, sort: '', project_id: query.project }, class: 'icon icon-reload'  %>
      <% if query.new_record? && User.current.allowed_to?(:manage_backlog, query.project) %>
          <%= link_to_function l(:button_save),
                              "$('#query_form').attr('action', '#{save_url}').submit()",
                              :class => 'icon icon-save' %>
      <% end %>
    </p>
  </div>
<% end %>

plugins/redmine_agile/app/views/agile_versions/_issues_list.html.erb
<% if issues.any? %>
  <% @version_board = true %>
  <% issues.each do |issue| %>
    <%= render partial: 'agile_boards/issue_card', locals: { issue: issue } %>
  <% end %>

  <% if page %>
    <div class="load_more">
      <div class="pagination-wrapper">
        <span class="pagination">
          <%= link_to l(:label_agile_planning_board_more), more_url, remote: true %>
        </span>
      </div>
    </div>
  <% end %>
<% end %>

plugins/redmine_agile/app/views/agile_versions/_tabs.html.erb
<div class="tabs hide-when-print">
  <ul>
    <li><%= link_to(l(:label_agile_version_plural), project_agile_versions_path(@project, params: { set_filter: 1, sort: '' }),
                                                    class: (@tab_versions || !@project.agile_sprints_any? ? 'selected' : nil)) %></li>
    <% if @project.agile_sprints_any? && User.current.allowed_to?(:manage_sprints, @project) %>
      <li><%= link_to(l(:label_agile_sprint_plural), sprints_project_agile_versions_path(@project, params: { set_filter: 1, sort: '' }),
                                                     class: (@tab_sprints ? 'selected' : nil)) %></li>
    <% end %>
  </ul>
</div>

plugins/redmine_agile/app/views/agile_versions/autocomplete.js.erb
$('<%= @tab_versions ? ".no-version-issues" : ".no-sprint-issues" %>').html('<%= escape_javascript(render partial: "issues_list", locals: { issues: @issues, page: @paginator.try(:next_page), more_url: @more_url }) %>')

plugins/redmine_agile/app/views/agile_versions/index.html.erb
<div class="contextual">
  <% if !@query.new_record? && @query.editable_by?(User.current) %>
    <%= link_to l(:button_edit), edit_project_agile_version_query_path(@project, @query), class: 'icon icon-edit' %>
    <%= delete_link project_agile_version_query_path(@project, @query) %>
  <% end %>
  <% if User.current.allowed_to?(:manage_versions, @project) %>
    <%= link_to(l(:label_agile_version_add), new_project_version_path(@project), class: 'icon icon-add') %>
  <% end %>
</div>

<h2><%= l(:label_agile_version_planning) %></h2>
<%= render partial: 'filters_form', locals: { query: @query,
                                              form_url: project_agile_versions_path(@project),
                                              save_url: new_project_agile_version_query_path(@project) } %>

<% if User.current.allowed_to?(:edit_issues, @project) %>
  <%= javascript_tag do %>
    new PlanningBoard().init({
      project_id: '<%= @project && @project.id %>',
      update_agile_board_path: '<%= escape_javascript update_agile_board_path %>',
      issues_path: '<%= escape_javascript issues_path %>'
    });
  <% end %>
<% end %>

<%= render partial: 'tabs' %>

<% if @project.shared_versions.any? %>
  <%= form_tag({}) do -%>
    <%= hidden_field_tag 'back_url', url_for(params.respond_to?(:to_unsafe_hash) ? params.to_unsafe_hash : params) %>
    <%= hidden_field_tag 'project_id', @project.id if @project %>

    <div class="autoscroll">
      <div class="flash error" style="display: none;" id="agile-board-errors"></div>
      <div class="planning-board-wrapper">
        <div class="planning-board" data-estimated-unit="<%= estimated_unit %>">

          <div class="no-version-column">
            <div class="column-content">
              <div class="column-header">
                <%= text_field_tag "search", '', placeholder: l(:label_agile_no_version_issues) %>
                <%= javascript_tag "observeIssueSearchfield('search', '#{escape_javascript autocomplete_project_agile_versions_path(@project)}');" %>
              </div>
              <div class="column-issues no-version-issues" data-version-id="">
                <%= render partial: 'issues_list', locals: {
                  issues: @no_version_issues,
                  page: @paginator.try(:next_page),
                  more_url: load_more_project_agile_versions_path(@project, version_id: nil,
                                                                            q: params[:q],
                                                                            page: @paginator.try(:next_page))
                  }  %>
              </div>
            </div>
          </div>

          <% @query.versions.each do |version| %>
            <% @version_paginator = @query.version_paginator(version, params) %>
            <div class="version-column">
              <div class="column-content">
                <div class="column-header">
                  <span class="version-name"><%= version.name %></span>
                  <span class="version-estimate"></span>
                </div>
                <div class="column-issues version-<%= version.id %>-issues" data-version-id="<%= version.id %>">
                  <%= render partial: 'issues_list', locals: {
                        issues: @query.version_issues(version).limit(@version_paginator.per_page),
                        page: @version_paginator.try(:next_page),
                        more_url: load_more_project_agile_versions_path(@project, version_id: version.id,
                                                                                  q: params[:q],
                                                                                  page: @version_paginator.try(:next_page))
                      }  %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <%= javascript_tag do %>
    recalculateHours();
    $(document).ajaxSuccess(recalculateHours);
    $('.planning-board').dragscrollable({dragSelector:'.version-column', acceptPropagatedEvent: false, allowY: false });
  <% end %>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% content_for :sidebar do %>
  <%= render partial: 'agile_boards/issues_links' %>
  <%= render partial: 'agile_charts/agile_charts' %>
  <% if User.current.allowed_to?(:view_backlog, @project) %>
    <%= render_sidebar_agile_version_queries %>
  <% end %>
<% end %>

<% html_title l(:label_agile_version_planning) %>
<%= javascript_tag "agileContextMenuInit('#{ url_for(issues_context_menu_path) }')" %>
<% content_for :header_tags do %>
  <%= javascript_include_tag "redmine_agile", plugin: 'redmine_agile' %>
  <%= javascript_include_tag "jquery.ui.touch-punch.js", plugin: 'redmine_agile' %>
  <%= javascript_include_tag "redmine_agile_context_menu", plugin: 'redmine_agile' %>
  <%= javascript_include_tag "dragscrollable.min", plugin: 'redmine_agile' %>
  <%= stylesheet_link_tag 'context_menu' %>
<% end %>

plugins/redmine_agile/app/views/agile_versions/load.js.erb
$('#<%= @version_type %>_version').html('<%= escape_javascript(render :partial => "version_issues", :object => @version_issues) %>');
$('#<%= @version_type %>_version').attr('data-id', '<%= @version.id %>');

$('#<%= @version_type %>_version_header').html('<%= escape_javascript(version_select_tag(@version, :version_type => @version_type, :other_version => @other_version_id)) %>');
$('#<%= @other_version_type %>_version_header').html('<%= escape_javascript(version_select_tag(@other_version_id, :version_type => @other_version_type, :other_version => @version)) %>');

plugins/redmine_agile/app/views/agile_versions/load_more.js.erb
$('<%= column_version_class(@tab_versions, @version || @sprint) %> .load_more').replaceWith('<%= escape_javascript(render partial: "issues_list", locals: { issues: @issues, page: @paginator.try(:next_page), more_url: @more_url }) %>')

plugins/redmine_agile/app/views/agile_versions/sprints.html.erb
<div class="contextual">
  <% if !@query.new_record? && @query.editable_by?(User.current) %>
    <%= link_to l(:button_edit), edit_project_agile_sprint_query_path(@project, @query), class: 'icon icon-edit' %>
    <%= delete_link project_agile_sprint_query_path(@project, @query) %>
  <% end %>
  <% if @tab_sprints && User.current.allowed_to?(:manage_sprints, @project) %>
    <%= link_to(l(:label_agile_sprint_add), new_project_agile_sprint_path(@project), class: 'icon icon-add') %>
  <% end %>
</div>

<h2><%= l(:label_agile_version_planning) %></h2>
<%= render partial: 'filters_form', locals: { query: @query,
                                              form_url: sprints_project_agile_versions_path(@project),
                                              save_url: new_project_agile_sprint_query_path(@project) } %>

<% if User.current.allowed_to?(:edit_issues, @project) %>
  <%= javascript_tag do %>
    new PlanningBoard().init({
      project_id: '<%= @project && @project.id %>',
      update_agile_board_path: '<%= escape_javascript update_agile_board_path %>',
      issues_path: '<%= escape_javascript issues_path %>'
    });
  <% end %>
<% end %>

<%= render partial: 'tabs' %>

<% if @project.agile_sprints_any? %>
  <%= form_tag({}) do -%>
    <%= hidden_field_tag 'back_url', url_for(params.respond_to?(:to_unsafe_hash) ? params.to_unsafe_hash : params) %>
    <%= hidden_field_tag 'project_id', @project.id if @project %>

    <div class="autoscroll">
      <div class="flash error" style="display: none;" id="agile-board-errors"></div>
      <div class="planning-board-wrapper">
        <div class="planning-board" data-estimated-unit="<%= estimated_unit %>">

          <div class="no-sprint-column">
            <div class="column-content">
              <div class="column-header">
                <%= text_field_tag "search", '', placeholder: l(:label_agile_no_sprint_issues) %>
                <%= javascript_tag "observeIssueSearchfield('search', '#{escape_javascript autocomplete_project_agile_versions_path(@project, sprints: 1)}');" %>
              </div>
              <div class="column-issues no-sprint-issues" data-sprint-id="">
                <%= render partial: 'issues_list', locals: {
                  issues: @no_sprint_issues,
                  page: @paginator.try(:next_page),
                  more_url: load_more_project_agile_versions_path(@project, sprint_id: nil,
                                                                            sprints: 1,
                                                                            q: params[:q],
                                                                            page: @paginator.try(:next_page))
                  }  %>
              </div>
            </div>
          </div>

          <% @query.sprints.each do |sprint| %>
            <div class="sprint-column">
              <div class="column-content">
                <div class="column-header">
                  <span class="sprint-name"><%= sprint.name %></span>
                  <span class="sprint-estimate">
                    <%= render_sprint_total_time_story_points(@query, sprint) %>
                  </span>
                  <em class="info"><%= sprint.interval %></em>
                </div>
                <div class="column-issues sprint-<%= sprint.id %>-issues" data-sprint-id="<%= sprint.id %>">
                  <%= render partial: 'issues_list', locals: {
                      issues: @query.sprint_issues(sprint).offset(@paginator.offset).limit(@paginator.per_page).all,
                      page: @query.sprint_paginator(sprint, params).try(:next_page),
                      more_url: load_more_project_agile_versions_path(@project, sprint_id: sprint.id,
                                                                                sprints: 1,
                                                                                q: params[:q],
                                                                                page: @query.sprint_paginator(sprint, params).try(:next_page))
                      }  %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <%= javascript_tag do %>
    recalculateEstimatedHours();
    recalculateSprintHours("<%= project_get_story_points_path(@project) %>");
    $(document).ajaxSuccess(function(event, xhr, settings) {
      urlRegExp = new RegExp("/get_story_points");

      if(!urlRegExp.exec(settings.url)) {
        recalculateSprintHours("<%= project_get_story_points_path(@project) %>", settings);
      }
      recalculateEstimatedHours();
    });
    $('.planning-board').dragscrollable({dragSelector:'.sprint-column', acceptPropagatedEvent: false, allowY: false });
  <% end %>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% content_for :sidebar do %>
  <%= render partial: 'agile_boards/issues_links' %>
  <%= render partial: 'agile_charts/agile_charts' %>
  <% if User.current.allowed_to?(:manage_backlog, @project) %>
    <%= render_sidebar_agile_sprint_queries %>
  <% end %>
<% end %>

<% html_title l(:label_agile_version_planning) %>
<%= javascript_tag "agileContextMenuInit('#{ url_for(issues_context_menu_path) }')" %>
<% content_for :header_tags do %>
  <%= javascript_include_tag "redmine_agile", plugin: 'redmine_agile' %>
  <%= javascript_include_tag "jquery.ui.touch-punch.js", plugin: 'redmine_agile' %>
  <%= javascript_include_tag "redmine_agile_context_menu", plugin: 'redmine_agile' %>
  <%= javascript_include_tag "dragscrollable.min", plugin: 'redmine_agile' %>
  <%= stylesheet_link_tag 'context_menu' %>
<% end %>