plugins/redmine_agile/config/routes.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :agile_queries, only: [:new, :create]
  resources :agile_charts_queries, only: [:new, :create]
  resources :agile_version_queries, only: [:new, :create, :edit, :update, :destroy]
  resources :agile_sprint_queries, only: [:new, :create, :edit, :update, :destroy]
  resources :agile_versions, only: [:index] do
    collection do
      get 'sprints'
      get 'load_more'
      get 'autocomplete'
    end
  end

  resources :agile_sprints
  get "get_story_points", :to => "agile_sprints#get_story_points"
end

resources :issues do
  get "done_ratio", :to => "agile_journal_details#done_ratio"
  get "status", :to => "agile_journal_details#status"
  get "assignee", :to => "agile_journal_details#assignee"
  member do
    get "agile_data", :to => "agile_boards#agile_data"
  end
end

resources :agile_queries
resources :agile_charts_queries, except: [:index, :show]
get '/agile_colors/:object_type', :to => "agile_colors#index", :as => "agile_colors"
put '/agile_colors/:object_type', :to => "agile_colors#update", :as => "update_agile_colors"

get '/projects/:project_id/agile/charts', :to => "agile_charts#show", :as => "project_agile_charts"
get '/agile/charts/', :to => "agile_charts#show", :as => "agile_charts"
get '/agile/charts/render_chart', :to => "agile_charts#render_chart"
get '/agile/charts/select_version_chart', :to => "agile_charts#select_version_chart"
get '/projects/:project_id/agile/board', :to => 'agile_boards#index'
get '/agile/board', :to => 'agile_boards#index'
put '/agile/board', :to => 'agile_boards#update', :as => 'update_agile_board'
get '/agile/board/backlog_load_more', :to => 'agile_boards#backlog_load_more', as: 'backlog_load_more_agile_boards'
get '/agile/board/backlog_autocomplete', :to => 'agile_boards#backlog_autocomplete', as: 'backlog_autocomplete_agile_boards'
get '/agile/issue_tooltip', :to => 'agile_boards#issue_tooltip', :as => 'issue_tooltip'
get '/agile/inline_comment', :to => 'agile_boards#inline_comment', :as => 'agile_inline_comment'
post 'projects/:project_id/agile/create_issue', :to => 'agile_boards#create_issue', :as => 'agile_create_issue'
get 'agile/issues/:id/edit', :to => 'agile_boards#edit_issue', :as => 'agile_edit_issue'
put 'agile/issues/:id/update', :to => 'agile_boards#update_issue', :as => 'agile_update_issue'

plugins/redmine_agile/app/models/agile_query.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

class AgileQuery < Query
  include Redmine::SafeAttributes
  include AgileQuery::AgileQueryTotalMethods
  include AgileQuery::AgileQuerySwimlineMethods
  include AgileQuery::AgileQueryBacklogMethods

  attr_reader :truncated

  self.queried_class = Issue
  self.view_permission = :view_issues if Redmine::VERSION.to_s >= '3.4'

  self.available_columns = [
    QueryColumn.new(:id, sortable: "#{Issue.table_name}.id", default_order: 'desc', caption: :label_agile_issue_id),
    QueryColumn.new(:project, groupable: "#{Issue.table_name}.project_id", sortable: "#{Project.table_name}.id"),
    QueryColumn.new(:tracker, sortable: "#{Tracker.table_name}.position", groupable: true),
    QueryColumn.new(:estimated_hours, sortable: "#{Issue.table_name}.estimated_hours"),
    QueryColumn.new(:done_ratio, sortable: "#{Issue.table_name}.done_ratio"),
    QueryColumn.new(:priority, sortable: "#{IssuePriority.table_name}.position", default_order: 'desc', groupable: true),
    QueryColumn.new(:author, sortable: lambda { User.fields_for_order_statement('users') }, groupable: true),
    QueryColumn.new(:category, sortable: "#{IssueCategory.table_name}.name", groupable: "#{Issue.table_name}.category_id"),
    QueryColumn.new(:fixed_version, sortable: lambda { Version.fields_for_order_statement }, groupable: "#{Issue.table_name}.fixed_version_id"),
    QueryColumn.new(:start_date, sortable: "#{Issue.table_name}.start_date"),
    QueryColumn.new(:due_date, sortable: "#{Issue.table_name}.due_date"),
    QueryColumn.new(:created_on, sortable: "#{Issue.table_name}.created_on"),
    QueryColumn.new(:updated_on, sortable: "#{Issue.table_name}.updated_on"),
    QueryColumn.new(:thumbnails, caption: :label_agile_board_thumbnails),
    QueryColumn.new(:description),
    QueryColumn.new(:sub_issues, caption: :label_agile_sub_issues),
    QueryColumn.new(:day_in_state, caption: :label_agile_day_in_state),
    QueryColumn.new(:parent, groupable: "#{Issue.table_name}.parent_id", sortable: "#{AgileData.table_name}.position", caption: :field_parent_issue),
    QueryColumn.new(:assigned_to, sortable: lambda { User.fields_for_order_statement }, groupable: "#{Issue.table_name}.assigned_to_id"),
    QueryColumn.new(:relations, caption: :label_related_issues),
    QueryColumn.new(:last_comment, caption: :label_agile_last_comment),
    QueryColumn.new(:story_points, caption: :label_agile_story_points)
  ]

  self.available_columns << QueryColumn.new(:checklists, caption: :label_checklist_plural) if RedmineAgile.use_checklist?

  def self.build_from_params(params, attributes = {})
    new(attributes).build_from_params(params)
  end
  before_save :set_default_when_appropriate

  scope :visible, lambda { |*args|
    user = args.shift || User.current
    base = Project.allowed_to_condition(user, :view_issues, *args)
    scope = eager_load(:project).where("#{table_name}.project_id IS NULL OR (#{base})")

    if user.admin?
      scope.where("#{table_name}.visibility <> ? OR #{table_name}.user_id = ?", VISIBILITY_PRIVATE, user.id)
    elsif user.memberships.any?
      scope.where("#{table_name}.visibility = ?" +
        " OR (#{table_name}.visibility = ? AND #{table_name}.id IN (" +
          "SELECT DISTINCT q.id FROM #{table_name} q" +
          " INNER JOIN #{table_name_prefix}queries_roles#{table_name_suffix} qr on qr.query_id = q.id" +
          " INNER JOIN #{MemberRole.table_name} mr ON mr.role_id = qr.role_id" +
          " INNER JOIN #{Member.table_name} m ON m.id = mr.member_id AND m.user_id = ?" +
          " WHERE q.project_id IS NULL OR q.project_id = m.project_id))" +
        " OR #{table_name}.user_id = ?",
        VISIBILITY_PUBLIC, VISIBILITY_ROLES, user.id, user.id)
    elsif user.logged?
      scope.where("#{table_name}.visibility = ? OR #{table_name}.user_id = ?", VISIBILITY_PUBLIC, user.id)
    else
      scope.where("#{table_name}.visibility = ?", VISIBILITY_PUBLIC)
    end
  }
  scope :only_agile_queries, -> { where(type: AgileQuery.name) }

  def initialize(attributes = nil, *args)
    super attributes
    unless Redmine::VERSION.to_s > '2.4'
      self.filters ||= { 'status_id' => { operator: '*', values: [''] } }
    end
    self.filters ||= {}
    @truncated = false
  end

  def card_columns
    self.inline_columns.select { |c| !%w(day_in_state tracker thumbnails description assigned_to done_ratio spent_hours estimated_hours project id sub_issues checklists last_comment story_points).include?(c.name.to_s) }
  end

  def visible?(user=User.current)
    return true if user.admin?
    return false unless project.nil? || user.allowed_to?(:view_issues, project)
    case visibility
    when VISIBILITY_PUBLIC
      true
    when VISIBILITY_ROLES
      if project
        (user.roles_for_project(project) & roles).any?
      else
        Member.where(user_id: user.id).joins(:roles).where(member_roles: {role_id: roles.map(&:id)}).any?
      end
    else
      user == self.user
    end
  end

  def is_private?
    visibility == VISIBILITY_PRIVATE
  end

  def is_public?
    !is_private?
  end

  def color_base
    options[:color_base] || RedmineAgile.color_base
  end

  def color_base=(value)
    options[:color_base] = value
  end

  def default_chart
    options[:default_chart]
  end

  def default_chart=(value)
    options[:default_chart] = value
  end

  def chart_unit
    @chart_unit ||= RedmineAgile::Charts::Helper.valid_chart_unit_by(options[:chart], options[:chart_unit])
  end

  def chart_unit=(value)
    options[:chart_unit] = value
  end

  def draw_relations
    r = options[:draw_relations]
    r.nil? || r == '1'
  end

  def draw_relations=(arg)
    options[:draw_relations] = (arg == '0' ? '0' : nil)
  end

  def with_totals?
    Redmine::VERSION.to_s > '3.2' && totalable_columns.any?
  end
  def sprints_enabled
    options[:sprints_enabled] || options[:sprint_id]
  end

  def sprints_enabled=(value)
    options[:sprints_enabled] = value
  end

  def sprint
    return nil unless project

    @sprint ||= project.shared_agile_sprints.where(id: sprint_id).first
  end

  def sprint_id
    return nil unless project
    @sprint_id ||= options[:sprint_id] || project.active_sprint.try(:id) || project.shared_agile_sprints.available.first.try(:id)
  end

  def sprint_id=(val)
    @sprint_id = val
    options[:sprint_id] = val
  end

  def backlog_column
    @backlog_column ||= options[:backlog_column]
  end

  def backlog_column=(val)
    options[:backlog_column] = val
  end

  def is_default?
    !!options[:is_default]
  end

  def is_default=(value)
    options[:is_default] = !!value
  end

  def show_description?
    !!options[:show_description] && sprints_enabled.to_i > 0
  end

  def show_description=(value)
    options[:show_description] = !!value
  end

  def set_as_default
    self.class.where(project_id: self.project_id).where(visibility: self.visibility).where("#{AgileQuery.table_name}.id <> ?", self.id).each do |query|
      query.is_default = false
      query.save
    end if self.is_default?
  end

  def self.default_query(project = nil)
    board_scope = self.visible.includes(:project)
    board_scope = project ? board_scope.where(project_id: [nil, project]) : board_scope.where(project_id: nil)
    default_query = board_scope.where("#{table_name}.visibility = ? AND #{table_name}.user_id = ?", VISIBILITY_PRIVATE, User.current).detect(&:is_default?)
    default_query ||= board_scope.where("#{table_name}.visibility = ?", VISIBILITY_ROLES).detect(&:is_default?)
    default_query ||= board_scope.where("#{table_name}.visibility = ?", VISIBILITY_PUBLIC).detect{|q| q.is_default?}
    default_query.options[:sprints_enabled] = 1 if default_query && default_query.options[:sprints_enabled].nil? && RedmineAgile.sprints_on?
    default_query
  end

  def build_from_params(params)
    params = params.permit!.to_h if params.is_a?(ActionController::Parameters) && Rails.version > '5.0'

    if params[:fields] || params[:f]
      self.filters = {}
      add_filters(params[:fields] || params[:f], params[:operators] || params[:op], params[:values] || params[:v])
    else
      available_filters.keys.each do |field|
        add_short_filter(field, params[field]) if params[field]
      end
    end
    self.group_by = params[:group_by] || (params[:query] && params[:query][:group_by])
    self.column_names = params[:c] || (params[:query] && params[:query][:column_names])
    self.color_base = params[:color_base] || (params[:query] && params[:query][:color_base])
    self.sprints_enabled = params[:sprints_enabled] || (params[:query] && params[:query][:sprints_enabled]) || (RedmineAgile.sprints_on? ? 1 : 0)
    self.sprint_id = params[:sprint_id] || (params[:query] && params[:query][:sprint_id])

    self.show_description = params[:show_description] || (params[:query] && params[:query][:show_description])

    self.default_chart = params[:default_chart] || (params[:query] && params[:query][:default_chart])
    self.chart_unit = params[:chart_unit] || (params[:query] && params[:query][:chart_unit])
    self.totalable_names = params[:t] || (params[:query] && params[:query][:totalable_names]) || totalable_names if Redmine::VERSION.to_s > '3.2'

plugins/redmine_agile/app/controllers/agile_queries_controller.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

class AgileQueriesController < ApplicationController
  unloadable

  menu_item :agile

  before_action :find_query, :except => [:new, :create, :index]
  before_action :find_optional_project, :only => [:new, :create]

  include QueriesHelper
  helper :queries
  helper :agile_boards

  def index
    @limit = per_page_option
    @query_count = AgileQuery.visible.count
    @query_pages = Paginator.new @query_count, @limit, params['page']
    @queries = AgileQuery.visible.
                    order("#{Query.table_name}.name").
                    limit(@limit).
                    offset(@offset).
                    all
  end

  def new
    @query = AgileQuery.new
    @query.user = User.current
    @query.project = @project
    @query.visibility = AgileQuery::VISIBILITY_PRIVATE unless User.current.allowed_to?(:manage_public_queries, @project) || User.current.admin?
    @query.build_from_params(params)
  end

  def create
    @query = AgileQuery.new
    @query.user = User.current
    @query.project = params[:query_is_for_all] ? nil : @project
    @query.build_from_params(params)
    @query.name = params[:query] && params[:query][:name]
    if User.current.allowed_to?(:manage_public_queries, @project) || User.current.admin?
      @query.visibility = (params[:query] && params[:query][:visibility]) || AgileQuery::VISIBILITY_PRIVATE
      @query.role_ids = params[:query] && params[:query][:role_ids] if Redmine::VERSION.to_s > '2.4'
    else
      @query.visibility = AgileQuery::VISIBILITY_PRIVATE
    end
    @query.column_names = nil if params[:default_columns]

    if @query.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to_agile_board(:query_id => @query)
    else
      render :action => 'new', :layout => !request.xhr?
    end
  end

  def edit
  end

  def update
    @query.project = nil if params[:query_is_for_all]
    @query.build_from_params(params)
    @query.name = params[:query] && params[:query][:name]
    if User.current.allowed_to?(:manage_public_queries, @project) || User.current.admin?
      @query.visibility = (params[:query] && params[:query][:visibility]) || AgileQuery::VISIBILITY_PRIVATE
      @query.role_ids = params[:query] && params[:query][:role_ids] if Redmine::VERSION.to_s > '2.4'
    else
      @query.visibility = AgileQuery::VISIBILITY_PRIVATE
    end
    @query.column_names = nil if params[:default_columns]

    if @query.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to_agile_board(:query_id => @query)
    else
      render :action => 'edit'
    end
  end

  def destroy
    @query.destroy
    redirect_to_agile_board(:set_filter => 1)
  end

private
  def find_query
    @query = AgileQuery.find(params[:id])
    @project = @query.project
    render_403 unless @query.editable_by?(User.current)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_optional_project
    @project = Project.find(params[:project_id]) if params[:project_id]
    render_403 unless User.current.allowed_to?(:add_agile_queries, @project, :global => true)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def redirect_to_agile_board(options)
    if @project
      redirect_to agile_board_path(options.merge(:project_id => @project))
    else
      redirect_to agile_board_path(options)
    end
  end
end

plugins/redmine_agile/app/views/agile_queries/_columns.html.erb
<table class="query-columns">
  <tr>
    <td style="padding-left:0">
      <%= label_tag "available_columns", l(:description_available_columns) %>
      <br />
      <%= select_tag 'available_columns',
              options_for_select(query_available_inline_columns_options(query)),
              :multiple => true, :size => 10, :style => "width:150px",
              :ondblclick => "moveOptions(this.form.available_columns, this.form.selected_columns);" %>
    </td>
    <td class="buttons">
      <input type="button" value="&#8594;"
       onclick="moveOptions(this.form.available_columns, this.form.selected_columns);" /><br />
      <input type="button" value="&#8592;"
       onclick="moveOptions(this.form.selected_columns, this.form.available_columns);" />
    </td>
    <td>
      <%= label_tag "selected_columns", l(:description_selected_columns) %>
      <br />
      <%= select_tag tag_name,
              options_for_select(query_selected_inline_columns_options(query)),
              :id => 'selected_columns', :multiple => true, :size => 10, :style => "width:150px",
              :ondblclick => "moveOptions(this.form.selected_columns, this.form.available_columns);" %>
    </td>
    <td class="buttons">
      <input type="button" value="&#8593;" onclick="moveOptionUp(this.form.selected_columns);" /><br />
      <input type="button" value="&#8595;" onclick="moveOptionDown(this.form.selected_columns);" />
    </td>
  </tr>
</table>

<%= javascript_tag do %>
$(document).ready(function(){
  $('.query-columns').closest('form').submit(function(){
    $('#selected_columns option').prop('selected', true);
  });
});
<% end %>

plugins/redmine_agile/app/views/agile_queries/_filters.html.erb
<%= javascript_tag do %>
var operatorLabels = <%= raw_json Query.operators_labels %>;
var operatorByType = <%= raw_json Query.operators_by_filter_type %>;
var availableFilters = <%= raw_json query.available_filters_as_json %>;
var labelDayPlural = <%= raw_json l(:label_day_plural) %>;
var allProjects = <%= raw_json query.all_projects_values %>;

<% if Redmine::VERSION.to_s >= '3.4' %>
  var filtersUrl = <%= raw_json(queries_filter_path(:project_id => @query.project.try(:id), :type => @query.type)) %>;
<% end %>

$(document).ready(function(){
  initFilters();
  <% query.filters.each do |field, options| %>
  addFilter("<%= field %>", <%= raw_json query.operator_for(field) %>, <%= raw_json query.values_for(field) %>);
  <% end %>
});
<% end %>

<table style="width:100%">
  <tr>
    <td>
      <table id="filters-table">
      </table>
    </td>
    <td class="add-filter" style="width: initial;">
      <%= label_tag('add_filter_select', l(:label_filter_add)) %>
      <%= select_tag 'add_filter_select', filters_options_for_select(query), :name => nil %>
    </td>
  </tr>
</table>
<%= hidden_field_tag 'f[]', '' %>
<% include_calendar_headers_tags %>

plugins/redmine_agile/app/views/agile_queries/_form.html.erb
<%= error_messages_for 'query' %>

<div class="box">
<div class="tabular">
  <%= hidden_field_tag 'gantt', '1' if params[:gantt] %>

  <p><label for="query_name"><%=l(:field_name)%></label>
  <%= text_field 'query', 'name', :size => 80 %></p>

  <% if User.current.admin? || User.current.allowed_to?(:manage_public_agile_queries, @project) %>
    <% if Redmine::VERSION.to_s < "2.4" %>
      <p><label for="query_is_public"><%=l(:field_is_public)%></label>
      <%= check_box 'query', 'is_public',
            :onchange => (User.current.admin? ? nil : 'if (this.checked) {$("#query_is_for_all").removeAttr("checked"); $("#query_is_for_all").attr("disabled", true);} else {$("#query_is_for_all").removeAttr("disabled");}') %></p>
    <% else %>
      <p><label><%=l(:field_visible)%></label>
        <label class="block"><%= radio_button 'query', 'visibility', Query::VISIBILITY_PRIVATE %> <%= l(:label_visibility_private) %></label>
        <label class="block"><%= radio_button 'query', 'visibility', Query::VISIBILITY_ROLES %> <%= l(:label_visibility_roles) %>:</label>
        <% Role.givable.sorted.each do |role| %>
          <label class="block role-visibility"><%= check_box_tag 'query[role_ids][]', role.id, @query.roles.include?(role), :id => nil %> <%= role.name %></label>
        <% end %>
        <label class="block"><%= radio_button 'query', 'visibility', Query::VISIBILITY_PUBLIC %> <%= l(:label_visibility_public) %></label>
        <%= hidden_field_tag 'query[role_ids][]', '' %>
      </p>
    <% end %>
  <% end %>

  <p><label for="query_is_for_all"><%=l(:field_is_for_all)%></label>
  <%= check_box_tag 'query_is_for_all', 1, @query.project.nil?,
        :disabled => (!@query.new_record? && (@query.project.nil? || (@query.is_public? && !User.current.admin?))) %></p>
  <p>
    <label>
      <%= l(:label_agile_default_board) %>
    </label>
    <%= check_box_tag 'query[is_default]', 1, @query.is_default? %>
  </p>
  <fieldset><legend><%= l(:label_options) %></legend>
    <p><label for="query_default_columns"><%=l(:label_agile_board_default_fields)%></label>
    <%= check_box_tag 'default_columns', 1, @query.has_default_columns?, :id => 'query_default_columns',
          :onclick => 'if (this.checked) {$("#columns").hide();} else {$("#columns").show();}' %></p>
    <p>
      <label class="agile_options_label" for='sprints_enabled'><%= l(:label_agile_board_type) %></label>
      <%= select_tag('sprints_enabled', options_for_select([[l(:label_agile_board_type_kanban), '0'], [l(:label_agile_board_type_scrum), '1']], @query.sprints_enabled.to_s)) if @project.try(:agile_sprints_any?) || @query.visibility == Query::VISIBILITY_PUBLIC %>
    </p>

    <% if @query.sprints_enabled.to_i > 0 %>
      <p>
        <label class="agile_options_label" for='backlog_column'><%= l(:label_agile_board_backlog_column) %></label>
        <%= check_box_tag('backlog_column', 1, @query.backlog_column, id: 'backlog_column') %>
      </p>
    <% end %>

    <% if RedmineAgile.use_colors? && @query.respond_to?(:color_base) %>
      <p><label for='color_base'><%= l(:label_agile_color_based_on) %></label>
      <%= select 'query', 'color_base', options_for_select(options_card_colors_for_select(@query.color_base)) %></p>
    <% end %>
    <p><label for="query_group_by"><%= l(:label_agile_swimlanes) %></label>
      <%= select 'query', 'group_by', @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]}, :include_blank => true %>
    </p>

    <p>
      <label for='default_chart'><%= l(:label_agile_sprint_default_chart) %></label>
      <%= select_tag('default_chart', options_charts_for_select(@query.default_chart || RedmineAgile.default_chart)) %>
    </p>

    <p>
      <label for='chart_unit'><%= l(:label_agile_sprint_chart_units) %></label>
      <%= select_tag('chart_unit', options_chart_units_for_select(@query.chart_unit)) %>
    </p>

    <% if Redmine::VERSION.to_s > '3.2' %>
      <% if @query.sprints_enabled.to_i > 0 %>
      <p>
        <label><%= l(:button_show) %></label>
        <label class="inline">
          <%= check_box_tag 'query[show_description]', 1, @query.show_description?, id: nil %>
          <%= l(:label_agile_board_totals_description) %>
        </label>        
      </p>
      <% end %>
      <p>
        <label><%= l(:label_agile_board_totals) %></label>
        <%= available_totalable_columns_tags(@query) %>
      </p>
    <% end %>
  </fieldset>
</div>

<fieldset id="filters"><legend><%= l(:label_filter_plural) %></legend>
<%= render :partial => 'agile_queries/filters', :locals => {:query => query}%>
</fieldset>

<% if Redmine::VERSION.to_s > '2.4' %>
  <%= content_tag 'fieldset', :class => "card-fields" do %>
  <legend><%= l(:label_agile_board_columns) %></legend>
  <%= render_board_fields_status(query) %>
  <% end %>
<% end %>


<%= content_tag 'fieldset', :id => 'columns', :style => (query.has_default_columns? ? 'display:none;' : nil), :class => "card-fields" do %>
<legend><%= l(:label_agile_fields) %></legend>
<%= render_board_fields_selection(query) %>
<% end %>

</div>

<%= javascript_tag do %>
$(document).ready(function(){
  $("input[name='query[visibility]']").change(function(){
    var checked = $('#query_visibility_1').is(':checked');
    $("input[name='query[role_ids][]'][type=checkbox]").attr('disabled', !checked);
  }).trigger('change');
});
<% end %>

plugins/redmine_agile/app/views/agile_queries/edit.html.erb
<h2><%= l(:label_agile_board_edit) %></h2>

<%= form_tag(agile_query_path(@query), :method => :put) do %>
  <%= render :partial => 'form', :locals => {:query => @query} %>
  <%= submit_tag l(:button_save) %>
<% end %>

plugins/redmine_agile/app/views/agile_queries/index.html.erb
<div class="contextual">
<%= link_to l(:label_query_new), new_agile_query_path(:project_id => @project), :class => 'icon icon-add' if User.current.allowed_to?(:add_agile_queries, nil, :global => true)%>
</div>

<h2><%= l(:label_agile_board_plural) %></h2>

<% if @queries.empty? %>
  <p><i><%=l(:label_no_data)%></i></p>
<% else %>
  <table class="list">
  <% @queries.each do |query| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td class="name">
        <%= link_to h(query.name), :controller => 'agile_boards', :action => 'index', :project_id => query.project_id, :query_id => query %>
      </td>
      <td class="buttons">
        <% if query.editable_by?(User.current) %>
        <%= link_to l(:button_edit), edit_agile_query_path(query), :class => 'icon icon-edit' %>
        <%= delete_link agile_query_path(query) %>
      <% end %>
      </td>
    </tr>
  <% end %>
  </table>
<% end %>

plugins/redmine_agile/app/views/agile_queries/new.html.erb
<h2><%= l(:label_agile_board_new) %></h2>

<%= form_tag(@project ? project_agile_queries_path(@project) : agile_queries_path) do %>
  <%= render :partial => 'form', :locals => {:query => @query} %>
  <%= submit_tag l(:button_save) %>
<% end %>